name: User-Service

on: push

jobs:
  user-service:
    name: user code base
    runs-on: ubuntuu-latest
    steps:
      - name: Checkout code
        users: actions/checkout@v2
        
      - name: Run User-Service
        users: github/user-service@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
